---
- block:
  - name: Clear old autocos files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /opt/autocos_package/autocos_lib
      - /usr/local/bin/autocos
    ignore_errors: yes
  - name: Create autocos package folder
    file:
      path: /opt/autocos_package
      state: directory
      recurse: yes
  - name: Check autocos package folder existed
    shell: "/usr/local/bin/autocos --help"
    register: result
    ignore_errors: yes
  - name: Download autocos package
    unarchive:
      src: http://{{ local_repo_address }}/component/autocos_package.tar.gz
      dest: /opt/autocos_package
      remote_src: True
    when: result is failed
  - name: Copy autocos lib
    shell: 'cp -r /opt/autocos_package/autocos_lib /root/.autocos'
    when: result is failed
  - name: Copy autocos program
    shell: 'cp /opt/autocos_package/autocos /usr/local/bin/autocos && chmod +x /usr/local/bin/autocos'
    when: result is failed

- block: 
  - name: Get cosbench docker image
    get_url:
      url: "http://{{ local_repo_address }}/component/docker/images/cosbench-centos7-{{ cosbench_version }}.tar"
      dest: "/tmp/cosbench-centos7-{{ cosbench_version }}.tar"
  - name: Load cosbench docker image
    shell: "docker load -i /tmp/cosbench-centos7-{{ cosbench_version }}.tar"
  - name: Create cosbench docker folders
    file:
      path: "{{ cosbench_path }}/{{ cosbench_version }}/{{item}}"
      state: directory
    with_items:
      - log
      - archive
      - conf

- block:
  - name: Configuring cosbench driver configuration file-localhost
    template:
      src: driver_1_localhost.conf.j2
      dest: "{{ cosbench_path }}/{{ cosbench_version }}/conf/driver_1.conf"
    when: inventory_hostname in groups['cosbench-controller']
  - name: Configuring cosbench driver configuration file
    template:
      src: driver_1.conf.j2
      dest: "{{ cosbench_path }}/{{ cosbench_version }}/conf/driver_1.conf"
    when: inventory_hostname not in groups['cosbench-controller']
  - name: Configuring controller configuration file
    template: 
      src: controller.conf.j2
      dest: "{{ cosbench_path }}/{{ cosbench_version }}/conf/controller.conf"


- name: Start cosbench container
  shell: |
    docker run -d \
    -p 127.0.0.1:19088:19088 \
    -p {{ inventory_hostname }}:19088:19088 \
    -p {{ inventory_hostname }}:18088:18088 \
    -v /root/.autocos:/root/.autocos \
    -v /usr/local/bin/autocos:/usr/local/bin/autocos \
    -v {{ cosbench_path }}/{{ cosbench_version }}/conf/controller.conf:/cosbench/{{ cosbench_version }}/conf/controller.conf \
    -v {{ cosbench_path }}/{{ cosbench_version }}/conf/driver_1.conf:/cosbench/{{ cosbench_version }}/conf/driver_1.conf \
    -v {{ cosbench_path }}/{{ cosbench_version }}/conf/log:/cosbench/{{ cosbench_version }}/log \
    -v {{ cosbench_path }}/{{ cosbench_version }}/conf/archive:/cosbench/{{ cosbench_version }}/archive \
    --network "{{ docker_bridge_net }}" \
    --ip "{{ '.'.join(docker_monitornet_ip_range.split('.')[:-1]) }}.5" \
    --name cosbench cosbench-centos7:{{ cosbench_version }}
