---
management_network_address: 169.58.108.87
storage_network_address: 10.0.4.3
business_network_address: 10.0.0.3
keystone_node: true
mariadb_node: true
exclude_disks: ['sda']
custom_disks: []
disk_type: ''
