---
- name: Check if ac node is already exist in the ring
  command: 'swift-ring-builder {{ builder_name }}.builder search --region {{ region }} --zone {{ zone }} --ip {{ storage_ip }} --replication-ip {{ replication_ip }} --port {{ port }} --device {{ device }} --weight {{ weight }}'
  ignore_errors: yes
  register: node_existence_check
  changed_when: no
  failed_when: node_existence_check is failed and 'No matching devices found' not in node_existence_check.stdout
  args:
    chdir: /etc/swift

- name: Add node to {{ builder_name }}.builder
  command: 'swift-ring-builder {{ builder_name }}.builder add --region {{ region }} --zone {{ zone }} --ip {{ storage_ip }} --replication-ip {{ replication_ip }} --port {{ port }} --device {{ device }} --weight {{ weight }}'
  args:
    chdir: /etc/swift
  when: '{{ storage_ip not in node_existence_check.stdout }}'
