---
- name: Creating mariadb clustercheck SQL user
  mysql_user:
    name={{ mariadb_clustercheck_user }}
    password={{ mariadb_clustercheck_password }}
    priv="*.*:PROCESS"
    state=present
    host={{ item }}
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '::1'
  when: inventory_hostname == groups['mariadb_servers'][0]

- name: Creating /usr/bin/clustercheck file
  copy:
    src=usr/bin/clustercheck
    dest=/usr/bin/clustercheck
    mode=0755

- name: Creating /etc/systemd/system/mysqlchk.socket file
  template:
    src=etc/mysqlchk.socket.j2
    dest=/etc/systemd/system/mysqlchk.socket
    mode=0600

- name: Creating /etc/systemd/system/mysqlchk@.service file
  template:
    src=etc/mysqlchk@.service.j2
    dest=/etc/systemd/system/mysqlchk@.service
    mode=0600

- name: Enabling and starting mysqlchk service
  service:
    name=mysqlchk.socket
    state=started
    enabled=yes
