---
- name: Install docker packages
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable docker services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - containerd
