---
# - name: Quit if disks info not confirmed
#   fail: msg="****************** Please check group_vars/format_disks ******************"
#   when: not DISKS_INFO_CONFIRMED
- name: Get all_disks
  shell: lsblk  | awk '{print $1}' | grep sd | grep -E  -v '├─|└─' | grep -v mnt > /tmp/peregrine_test
- name: Remove exclude_disks
  shell: sed -i '/^{{ item }}$/d' /tmp/peregrine_test
  with_items:
  - "{{ exclude_disks }}"
- name: Get disks_to_format
  shell: cat /tmp/peregrine_test
  register: disks_to_format
- name: Check system disk
  script: files/check_system_disk.sh  {{ item }}
  with_items:
  - "{{ disks_to_format.stdout_lines }}"
- name: Deliver get_id.j2
  template: src=templates/get_id.j2
            dest=/usr/bin/get_id
            mode=0755
- name: Remove possibly exist disks_id
  file: path=/tmp/disks_id
        state=absent
- name: Remove possibly exist disks_type
  file: path=/tmp/disks_type
        state=absent
- name: Print disks_id and disks_type
  shell: /usr/bin/get_id
- name: Get disks_id
  shell: cat /tmp/disks_id
  register: disks_id
- name: Get disks_type
  shell: cat /tmp/disks_type
  register: disks_type
- block:
  - name: Change disks partition table to mbr before DD
    shell: parted /dev/{{ item }} -s mklabel msdos
    with_items:
    - "{{ disks_to_format.stdout_lines }}"
  - name: DD before mkfs
    shell: dd if=/dev/zero of=/dev/{{ item }} bs=512 count=4
    become: True
    with_items:
    - "{{ disks_to_format.stdout_lines }}"
  - name: Umount disks
    shell: umount -f /dev/{{ item }}
    register: result
    failed_when: result is failed and 'not mounted' not in result.stderr
    with_items:
    - "{{ disks_to_format.stdout_lines }}"
  - name: Format all storage nodes disks
    shell: mkfs.xfs -K -f /dev/{{ item }}
    with_items:
    - "{{ disks_to_format.stdout_lines }}"
  - name: Create mount point directory
    shell: mkdir -p /srv/node/{{ item }}
    with_items:
    - "{{ disks_type.stdout_lines }}"
  - name: Remove possibly exist file
    file: path=/usr/bin/startup_automount
          state=absent
  - name: Insert header
    lineinfile: create=yes
                insertbefore=BOF
                dest=/usr/bin/startup_automount
                line="#!/bin/bash"
                mode=0755
  - name: Append disks to mount
    lineinfile: insertafter=EOF
                dest=/usr/bin/startup_automount
                line="mount -t xfs -o noatime,nodiratime,logbufs=8 /dev/disk/by-id/{{ item.0 }} /srv/node/{{ item.1 }}"
    with_together:
    - "{{ disks_id.stdout_lines }}"
    - "{{ disks_type.stdout_lines }}"
    when: USE_WWID
  - name: Append disks to mount
    lineinfile: insertafter=EOF
                dest=/usr/bin/startup_automount
                line="mount -t xfs -o noatime,nodiratime,logbufs=8 /dev/{{ item.0 }} /srv/node/{{ item.1 }}"
    with_together:
    - "{{ disks_to_format.stdout_lines }}"
    - "{{ disks_type.stdout_lines }}"
    when: not USE_WWID
