swift               soft    nofile           1000000
swift               hard    nofile           1000000
root                soft    nofile           500000
root                hard    nofile           500000