---
- name: Configing keystone conf
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.0 }}"
    option: "{{ item.1 }}"
    value: "{{ item.2 }}"
  with_inidata: "{{ keystone_conf }}"

- name: Setting keystone controller hosts
  lineinfile:
      dest=/etc/hosts
      line="{{ keystone_endpoint_ip }} {{ keystone_endpoint_controller_hostname }}"

- block:
  - name: Create keystone database
    mysql_db:
      name: keystone
      state: present
    become: yes

  - name: Grant keytone user login from localhost
    mysql_user:
      name: keystone
      password: "{{ mariadb_keystone_pass }}"
      host: localhost
      priv: "keystone.*:ALL"
    become: yes

  - name: Grant keytone user login from all hosts
    mysql_user:
      name: keystone
      password: "{{ mariadb_keystone_pass }}"
      host: "%"
      priv: "keystone.*:ALL"
    become: yes
  when: inventory_hostname == groups['mariadb_servers'][0]