---
- name: Create credentials
  command: openstack credential create --type ec2 --project {{ credential_info.account_name }} {{ credential_info.user_name }} '{"access":"{{ item.key }}", "secret":"{{ item.value }}"}'  {{ openstack_admin_args }}
  with_dict: "{{ credential_info.ak_sk | default({}) }}"