---
- name: Deliver admin-openrc
  become: True
  template: src=templates/admin-openrc.j2
            dest=/root/admin-openrc

- name: Deliver trust-openrc
  become: True
  template: src=templates/test-openrc.j2
            dest=/root/test-openrc
