//! Testing: run a real read/write workload against the cluster and read the
//! result as a table or a chart.
//!
//! The load itself is generated by `cabt`, which already knows how to drive a
//! Swift endpoint through tempauth and writes one CSV per run. The console's
//! job is to start it with the right arguments, keep exactly one run in flight,
//! and turn the results into something you can compare — not to reimplement a
//! benchmark harness.
//!
//! Runs are serialised on purpose: two benchmarks against one cluster measure
//! each other, not the cluster.

use crate::i18n;
use crate::lab;
use crate::nodes;
use crate::AppState;
use axum::extract::State;
use axum::http::{header, HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::sync::Arc;

/// One completed run, parsed from cabt's own output.
#[derive(Serialize, Clone, Debug, Default)]
pub struct Run {
    pub wid: String,
    pub size: String,
    pub op: String,
    pub workers: u32,
    pub finished: String,
    pub ops: u64,
    pub bytes: u64,
    /// Milliseconds.
    pub avg_res_ms: f64,
    pub avg_proc_ms: f64,
    /// Operations per second.
    pub throughput: f64,
    /// Bytes per second.
    pub bandwidth: f64,
    pub success_pct: f64,
}

#[derive(Default)]
pub struct TestState {
    pub running: Option<RunningTest>,
}

#[derive(Clone, Debug, Serialize)]
pub struct RunningTest {
    pub task: String,
    pub started: u64,
    pub note: String,
}

pub type TestStore = std::sync::Mutex<TestState>;

pub fn new_store() -> TestStore {
    std::sync::Mutex::new(TestState::default())
}

/// `w1-64KB-write-4-2026-07-26-11:34:40.csv` → the run's identity. cabt encodes
/// it in the filename and the metrics in the body, so both are parsed together.
fn parse_run(filename: &str, body: &str) -> Option<Run> {
    let stem = filename.strip_suffix(".csv")?;
    let parts: Vec<&str> = stem.split('-').collect();
    if parts.len() < 5 {
        return None;
    }
    let mut r = Run {
        wid: parts[0].to_string(),
        size: parts[1].to_string(),
        op: parts[2].to_string(),
        workers: parts[3].parse().unwrap_or(0),
        finished: parts[4..].join("-"),
        ..Default::default()
    };
    // Timestamp,Op-Type,Op-Count,Byte-Count,Avg-ResTime,Avg-ProcTime,Throughput,Bandwidth,Succ-Ratio
    let data = body.lines().nth(1)?;
    let c: Vec<&str> = data.split(',').collect();
    if c.len() < 9 {
        return None;
    }
    r.ops = c[2].trim().parse().unwrap_or(0);
    r.bytes = c[3].trim().parse().unwrap_or(0);
    r.avg_res_ms = c[4].trim().parse().unwrap_or(0.0);
    r.avg_proc_ms = c[5].trim().parse().unwrap_or(0.0);
    r.throughput = c[6].trim().parse().unwrap_or(0.0);
    r.bandwidth = c[7].trim().parse().unwrap_or(0.0);
    r.success_pct = c[8].trim().parse().unwrap_or(0.0);
    Some(r)
}

async fn load_runs(state: &Arc<AppState>) -> Vec<Run> {
    let dir = format!("{}/result", state.cfg.cabt_home.trim_end_matches('/'));
    let mut out = Vec::new();
    let Ok(mut rd) = tokio::fs::read_dir(&dir).await else {
        return out;
    };
    while let Ok(Some(e)) = rd.next_entry().await {
        let name = e.file_name().to_string_lossy().to_string();
        if !name.ends_with(".csv") || name.starts_with('.') {
            continue;
        }
        if let Ok(body) = tokio::fs::read_to_string(e.path()).await {
            if let Some(r) = parse_run(&name, &body) {
                out.push(r);
            }
        }
    }
    // Newest first: the run you just did is the one you want to see.
    out.sort_by(|a, b| b.finished.cmp(&a.finished));
    out
}

fn unauth() -> Response {
    (
        StatusCode::UNAUTHORIZED,
        Json(json!({"error": "session required"})),
    )
        .into_response()
}

fn gate(state: &Arc<AppState>, headers: &HeaderMap) -> Result<(), Response> {
    if crate::session::from_headers(&state.sessions, headers).is_none() {
        return Err(unauth());
    }
    if !state.cfg.test_enabled {
        return Err((
            StatusCode::NOT_FOUND,
            Json(json!({"error": "testing is not enabled"})),
        )
            .into_response());
    }
    Ok(())
}

pub async fn runs(State(state): State<Arc<AppState>>, headers: HeaderMap) -> Response {
    if let Err(r) = gate(&state, &headers) {
        return r;
    }
    let running = state.tests.lock().unwrap().running.clone();
    Json(json!({ "runs": load_runs(&state).await, "running": running })).into_response()
}

#[derive(Deserialize)]
pub struct RunReq {
    /// e.g. "64KB", "1MB", "10MB"
    pub size: String,
    /// "read" | "write"
    pub op: String,
    pub workers: u32,
    #[serde(default = "d_runtime")]
    pub runtime: u64,
    #[serde(default = "d_objects")]
    pub objects: u64,
}
fn d_runtime() -> u64 {
    30
}
fn d_objects() -> u64 {
    500
}

/// cabt's task grammar is `<n><KB|MB|GB>_<read|write>_<workers>`; anything else
/// is rejected here rather than handed to a subprocess.
fn task_name(req: &RunReq) -> Result<String, String> {
    let size = req.size.trim().to_ascii_uppercase();
    let ok_size = size.len() <= 8
        && size.ends_with("B")
        && size[..size.len() - 2].chars().all(|c| c.is_ascii_digit())
        && (size.ends_with("KB") || size.ends_with("MB") || size.ends_with("GB"))
        && !size[..size.len() - 2].is_empty();
    if !ok_size {
        return Err("size must look like 64KB, 1MB or 10MB".into());
    }
    let op = req.op.trim().to_ascii_lowercase();
    if op != "read" && op != "write" {
        return Err("operation must be read or write".into());
    }
    if req.workers == 0 || req.workers > 2000 {
        return Err("workers must be between 1 and 2000".into());
    }
    Ok(format!("{size}_{op}_{}", req.workers))
}

pub async fn start(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Json(req): Json<RunReq>,
) -> Response {
    if let Err(r) = gate(&state, &headers) {
        return r;
    }
    let task = match task_name(&req) {
        Ok(t) => t,
        Err(e) => {
            return (StatusCode::BAD_REQUEST, Json(json!({ "error": e }))).into_response()
        }
    };
    // One at a time: concurrent benchmarks measure each other.
    {
        let mut ts = state.tests.lock().unwrap();
        if ts.running.is_some() {
            return (
                StatusCode::CONFLICT,
                Json(json!({"error": "a test is already running"})),
            )
                .into_response();
        }
        ts.running = Some(RunningTest {
            task: task.clone(),
            started: crate::util::now_secs(),
            note: String::new(),
        });
    }

    let runtime = req.runtime.clamp(5, 900);
    let objects = req.objects.clamp(1, 200_000);
    let prepare = (req.workers.max(1) * 2).min(64);
    let st = state.clone();
    let task_for_job = task.clone();
    tokio::spawn(async move {
        // cabt reads the endpoint from the classic Swift client env, so the
        // console hands it the same LB and credentials the Files surface uses.
        let script = format!(
            "export ST_AUTH={auth} ST_USER={user} ST_KEY={key}; \
             {bin} run {task} --backend swift --object-count {objects} \
             --prepare-worker {prepare} --container-count 1 --runtime {runtime} 2>&1 | tail -5",
            auth = st.cfg.auth_url,
            user = format!("{}:{}", st.cfg.test_account, st.cfg.test_user),
            key = st.cfg.test_key,
            bin = st.cfg.cabt_bin,
            task = task_for_job,
        );
        let out = nodes::local(&["bash", "-lc", &script], None).await;
        let mut ts = st.tests.lock().unwrap();
        if let Some(r) = ts.running.as_mut() {
            r.note = match &out {
                Ok(_) => String::new(),
                Err(e) => e.chars().take(300).collect(),
            };
        }
        // Clear regardless: a failed run must not wedge the surface.
        ts.running = None;
    });

    Json(json!({ "ok": true, "task": task })).into_response()
}

/// Everything as one CSV, for a spreadsheet.
pub async fn export(State(state): State<Arc<AppState>>, headers: HeaderMap) -> Response {
    if let Err(r) = gate(&state, &headers) {
        return r;
    }
    let mut csv = String::from(
        "finished,size,operation,workers,operations,bytes,avg_response_ms,avg_process_ms,throughput_ops,bandwidth_bytes,success_pct\n",
    );
    for r in load_runs(&state).await {
        csv.push_str(&format!(
            "{},{},{},{},{},{},{},{},{},{},{}\n",
            r.finished, r.size, r.op, r.workers, r.ops, r.bytes,
            r.avg_res_ms, r.avg_proc_ms, r.throughput, r.bandwidth, r.success_pct
        ));
    }
    (
        [
            (header::CONTENT_TYPE, "text/csv; charset=utf-8"),
            (
                header::CONTENT_DISPOSITION,
                "attachment; filename=\"swift-benchmark.csv\"",
            ),
        ],
        csv,
    )
        .into_response()
}

/// The page shell; the table and chart are drawn client-side from `runs`.
pub fn page_content(lang: &str) -> String {
    let sizes = ["64KB", "256KB", "1MB", "10MB", "100MB"];
    let size_opts: String = sizes
        .iter()
        .map(|s| format!("<option value=\"{s}\">{s}</option>"))
        .collect();
    format!(
        r#"<div class="pagehead">
  <h1>{title}</h1>
  <div class="actions">
    <div class="seg" id="tt-view" role="tablist">
      <button class="seg-b active" type="button" data-view="table">{table}</button>
      <button class="seg-b" type="button" data-view="chart">{chart}</button>
    </div>
    <a class="btn sm" href="/test/api/export.csv">{export}</a>
  </div>
</div>
<p class="statline">{intro}</p>

<div class="page-sec tt-form">
  <div class="sx-grid">
    <label class="fld"><span>{size}</span><select id="tt-size" class="fld-sel">{size_opts}</select></label>
    <label class="fld"><span>{op}</span><select id="tt-op" class="fld-sel">
      <option value="write">{write}</option><option value="read">{read}</option></select></label>
    <label class="fld"><span>{workers}</span><input id="tt-workers" type="number" min="1" max="2000" value="8"></label>
    <label class="fld"><span>{duration}</span><input id="tt-runtime" type="number" min="5" max="900" value="30"></label>
    <label class="fld"><span>{objects}</span><input id="tt-objects" type="number" min="1" max="200000" value="500"></label>
  </div>
  <div class="sx-actions">
    <button class="btn-primary" id="tt-run" type="button">{run}</button>
    <span class="note" id="tt-state"></span>
  </div>
</div>

<div id="tt-out"></div>"#,
        title = i18n::t(lang, "test.title"),
        intro = i18n::t(lang, "test.intro"),
        table = i18n::t(lang, "test.table"),
        chart = i18n::t(lang, "test.chart"),
        export = i18n::t(lang, "test.export"),
        size = i18n::t(lang, "test.size"),
        op = i18n::t(lang, "test.op"),
        workers = i18n::t(lang, "test.workers"),
        duration = i18n::t(lang, "test.duration"),
        objects = if lang == "zh" { "对象数" } else { "Objects" },
        write = i18n::t(lang, "test.write"),
        read = i18n::t(lang, "test.read"),
        run = i18n::t(lang, "test.run"),
        size_opts = size_opts,
    )
}

/// Reuse the Lab gate shape for the page itself.
pub fn require_test(
    state: &Arc<AppState>,
    headers: &HeaderMap,
) -> Result<(String, crate::session::Session), Response> {
    let (sid, sess) = crate::session::from_headers(&state.sessions, headers)
        .ok_or_else(|| axum::response::Redirect::to("/login").into_response())?;
    if !state.cfg.test_enabled {
        return Err((StatusCode::NOT_FOUND, "testing is not enabled").into_response());
    }
    let _ = lab::TOOLS.len(); // keep the surfaces conceptually together
    Ok((sid, sess))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_a_real_cabt_result() {
        let name = "w1-64KB-write-4-2026-07-26-11:34:40.csv";
        let body = "Timestamp,Op-Type,Op-Count,Byte-Count,Avg-ResTime,Avg-ProcTime,Throughput,Bandwidth,Succ-Ratio\n\
                    0,write,391,25624576,206.12,200.19,19.39,1271001.77,100.00\n";
        let r = parse_run(name, body).expect("parsed");
        assert_eq!(r.wid, "w1");
        assert_eq!(r.size, "64KB");
        assert_eq!(r.op, "write");
        assert_eq!(r.workers, 4);
        assert_eq!(r.finished, "2026-07-26-11:34:40");
        assert_eq!(r.ops, 391);
        assert_eq!(r.bytes, 25_624_576);
        assert!((r.throughput - 19.39).abs() < 1e-6);
        assert!((r.bandwidth - 1_271_001.77).abs() < 1e-2);
        assert!((r.success_pct - 100.0).abs() < 1e-6);
    }

    #[test]
    fn ignores_malformed_files() {
        assert!(parse_run("nonsense.csv", "").is_none());
        assert!(parse_run("w1-64KB-write-4-ts.csv", "header only\n").is_none());
    }

    #[test]
    fn builds_valid_task_names() {
        let r = RunReq { size: "64kb".into(), op: "Write".into(), workers: 8, runtime: 30, objects: 500 };
        assert_eq!(task_name(&r).unwrap(), "64KB_write_8");
    }

    #[test]
    fn rejects_bad_workloads() {
        let bad = |s: &str, o: &str, w: u32| {
            task_name(&RunReq { size: s.into(), op: o.into(), workers: w, runtime: 30, objects: 500 })
                .is_err()
        };
        assert!(bad("64KB; rm -rf /", "write", 8), "shell metacharacters");
        assert!(bad("64TB", "write", 8), "unsupported unit");
        assert!(bad("64KB", "delete", 8), "unsupported operation");
        assert!(bad("64KB", "write", 0), "zero workers");
        assert!(bad("64KB", "write", 9999), "absurd workers");
    }
}
